
let AttributeCodes = {
    1: {Code: "AGENCY", Description: "Agency responsible for production" },
    10: {Code: "CATBUA", Description: "Category of built-up area" },
    100: {Code: "HORWID", Description: "Horizontal width" },
    1001: {Code: "CATBUI", Description: "Category of building, single" },
    1002: {Code: "CATDYK", Description: "Category of dyke" },
    1003: {Code: "CATMST", Description: "Category of mast" },
    1004: {Code: "CATPRI", Description: "Category of production installation" },
    1005: {Code: "CATREB", Description: "Category of religious building" },
    1006: {Code: "CATTOW", Description: "Category of tower" },
    1007: {Code: "CATTRE", Description: "Category of tree" },
    1008: {Code: "COLMAR", Description: "Colour of navigational mark" },
    1009: {Code: "QUAVEM", Description: "Quality of vertical measurement" },
    101: {Code: "ICEFAC", Description: "Ice factor" },
    1010: {Code: "SUPLIT", Description: "Supervision of light" },
    1011: {Code: "CATMNT", Description: "Category of monument" },
    102: {Code: "INFORM", Description: "Information" },
    103: {Code: "JRSDTN", Description: "Jurisdiction" },
    104: {Code: "$JUSTH", Description: "Justification - horizontal" },
    105: {Code: "$JUSTV", Description: "Justification - vertical" },
    106: {Code: "LIFCAP", Description: "Lifting capacity" },
    107: {Code: "LITCHR", Description: "Light characteristic" },
    108: {Code: "LITVIS", Description: "Light visibility" },
    109: {Code: "MARSYS", Description: "Marks navigational - System of" },
    11: {Code: "CATCBL", Description: "Category of cable" },
    110: {Code: "MLTYLT", Description: "Multiplicity of lights" },
    111: {Code: "NATION", Description: "Nationality" },
    112: {Code: "NATCON", Description: "Nature of construction" },
    113: {Code: "NATSUR", Description: "Nature of surface" },
    114: {Code: "NATQUA", Description: "Nature of surface - qualifying terms" },
    115: {Code: "NMDATE", Description: "Notice to Mariners date" },
    116: {Code: "OBJNAM", Description: "Object name" },
    117: {Code: "ORIENT", Description: "Orientation" },
    118: {Code: "PEREND", Description: "Periodic date end" },
    119: {Code: "PERSTA", Description: "Periodic date start" },
    12: {Code: "CATCAN", Description: "Category of canal" },
    120: {Code: "PICREP", Description: "Pictorial representation" },
    121: {Code: "PILDST", Description: "Pilot district" },
    122: {Code: "PRCTRY", Description: "Producing country" },
    123: {Code: "PRODCT", Description: "Product" },
    124: {Code: "PUBREF", Description: "Publication reference" },
    125: {Code: "QUASOU", Description: "Quality of sounding measurement" },
    126: {Code: "RADWAL", Description: "Radar wave length" },
    127: {Code: "RADIUS", Description: "Radius" },
    128: {Code: "RECDAT", Description: "Recording date" },
    129: {Code: "RECIND", Description: "Recording indication" },
    13: {Code: "CATCAM", Description: "Category of cardinal mark" },
    130: {Code: "RYRMGV", Description: "Reference year for magnetic variation" },
    131: {Code: "RESTRN", Description: "Restriction" },
    132: {Code: "SCAMAX", Description: "Scale maximum" },
    133: {Code: "SCAMIN", Description: "Scale minimum" },
    134: {Code: "SCVAL1", Description: "Scale value one" },
    135: {Code: "SCVAL2", Description: "Scale value two" },
    136: {Code: "SECTR1", Description: "Sector limit one" },
    137: {Code: "SECTR2", Description: "Sector limit two" },
    138: {Code: "SHIPAM", Description: "Shift parameters" },
    139: {Code: "SIGFRQ", Description: "Signal frequency" },
    14: {Code: "CATCHP", Description: "Category of checkpoint" },
    140: {Code: "SIGGEN", Description: "Signal generation" },
    141: {Code: "SIGGRP", Description: "Signal group" },
    142: {Code: "SIGPER", Description: "Signal period" },
    143: {Code: "SIGSEQ", Description: "Signal sequence" },
    144: {Code: "SOUACC", Description: "Sounding accuracy" },
    145: {Code: "SDISMX", Description: "Sounding distance - maximum" },
    146: {Code: "SDISMN", Description: "Sounding distance - minimum" },
    147: {Code: "SORDAT", Description: "Source date" },
    148: {Code: "SORIND", Description: "Source indication" },
    149: {Code: "STATUS", Description: "Status" },
    15: {Code: "CATCOA", Description: "Category of coastline" },
    150: {Code: "SURATH", Description: "Survey authority" },
    151: {Code: "SUREND", Description: "Survey date - end" },
    152: {Code: "SURSTA", Description: "Survey date - start" },
    153: {Code: "SURTYP", Description: "Survey type" },
    154: {Code: "$SCALE", Description: "Symbol scaling factor" },
    155: {Code: "$SCODE", Description: "Symbolization code" },
    156: {Code: "TECSOU", Description: "Technique of sounding measurement" },
    157: {Code: "$TXSTR", Description: "Text string" },
    158: {Code: "TXTDSC", Description: "Textual description" },
    159: {Code: "TS_TSP", Description: "Tidal stream - panel values" },
    16: {Code: "CATCTR", Description: "Category of control point" },
    160: {Code: "TS_TSV", Description: "Tidal stream, current - time series values" },
    161: {Code: "T_ACWL", Description: "Tide - accuracy of water level" },
    162: {Code: "T_HWLW", Description: "Tide - high and low water values" },
    163: {Code: "T_MTOD", Description: "Tide - method of tidal prediction" },
    164: {Code: "T_THDF", Description: "Tide - time and height differences" },
    165: {Code: "T_TINT", Description: "Tide, current - time interval of values" },
    166: {Code: "T_TSVL", Description: "Tide - time series values" },
    167: {Code: "T_VAHC", Description: "Tide - value of harmonic constituents" },
    168: {Code: "TIMEND", Description: "Time end" },
    169: {Code: "TIMSTA", Description: "Time start" },
    17: {Code: "CATCON", Description: "Category of conveyor" },
    170: {Code: "$TINTS", Description: "Tint" },
    171: {Code: "TOPSHP", Description: "Topmark/daymark shape" },
    172: {Code: "TRAFIC", Description: "Traffic flow" },
    173: {Code: "VALACM", Description: "Value of annual change in magnetic variation" },
    174: {Code: "VALDCO", Description: "Value of depth contour" },
    175: {Code: "VALLMA", Description: "Value of local magnetic anomaly" },
    176: {Code: "VALMAG", Description: "Value of magnetic variation" },
    177: {Code: "VALMXR", Description: "Value of maximum range" },
    178: {Code: "VALNMR", Description: "Value of nominal range" },
    179: {Code: "VALSOU", Description: "Value of sounding" },
    18: {Code: "CATCOV", Description: "Category of coverage" },
    180: {Code: "VERACC", Description: "Vertical accuracy" },
    181: {Code: "VERCLR", Description: "Vertical clearance" },
    182: {Code: "VERCCL", Description: "Vertical clearance, closed" },
    183: {Code: "VERCOP", Description: "Vertical clearance, open" },
    184: {Code: "VERCSA", Description: "Vertical clearance, safe" },
    185: {Code: "VERDAT", Description: "Vertical datum" },
    186: {Code: "VERLEN", Description: "Vertical length" },
    187: {Code: "WATLEV", Description: "Water level effect" },
    188: {Code: "CAT_TS", Description: "Category of Tidal Stream" },
    189: {Code: "PUNITS", Description: "Positional accuracy units" },
    19: {Code: "CATCRN", Description: "Category of crane" },
    190: {Code: "CLSDEF", Description: "Object class definition" },
    191: {Code: "CLSNAM", Description: "Object class name" },
    192: {Code: "SYMINS", Description: "Symbol instruction" },
    2: {Code: "BCNSHP", Description: "Beacon shape" },
    20: {Code: "CATDAM", Description: "Category of dam" },
    21: {Code: "CATDIS", Description: "Category of distance mark" },
    22: {Code: "CATDOC", Description: "Category of dock" },
    23: {Code: "CATDPG", Description: "Category of dumping ground" },
    24: {Code: "CATFNC", Description: "Category of fence/wall" },
    25: {Code: "CATFRY", Description: "Category of ferry" },
    26: {Code: "CATFIF", Description: "Category of fishing facility" },
    27: {Code: "CATFOG", Description: "Category of fog signal" },
    28: {Code: "CATFOR", Description: "Category of fortified structure" },
    29: {Code: "CATGAT", Description: "Category of gate" },
    3: {Code: "BUISHP", Description: "Building shape" },
    30: {Code: "CATHAF", Description: "Category of harbour facility" },
    300: {Code: "NINFOM", Description: "Information in national language" },
    301: {Code: "NOBJNM", Description: "Object name in national language" },
    302: {Code: "NPLDST", Description: "Pilot district in national language" },
    303: {Code: "$NTXST", Description: "Text string in national language" },
    304: {Code: "NTXTDS", Description: "Textual description in national language" },
    31: {Code: "CATHLK", Description: "Category of hulk" },
    32: {Code: "CATICE", Description: "Category of ice" },
    33: {Code: "CATINB", Description: "Category of installation buoy" },
    34: {Code: "CATLND", Description: "Category of land region" },
    35: {Code: "CATLMK", Description: "Category of landmark" },
    36: {Code: "CATLAM", Description: "Category of lateral mark" },
    37: {Code: "CATLIT", Description: "Category of light" },
    38: {Code: "CATMFA", Description: "Category of marine farm/culture" },
    39: {Code: "CATMPA", Description: "Category of military practice area" },
    4: {Code: "BOYSHP", Description: "Buoy shape" },
    40: {Code: "CATMOR", Description: "Category of mooring/warping facility" },
    400: {Code: "HORDAT", Description: "Horizontal datum" },
    401: {Code: "POSACC", Description: "Positional Accuracy" },
    402: {Code: "QUAPOS", Description: "Quality of position" },
    41: {Code: "CATNAV", Description: "Category of navigation line" },
    42: {Code: "CATOBS", Description: "Category of obstruction" },
    43: {Code: "CATOFP", Description: "Category of offshore platform" },
    44: {Code: "CATOLB", Description: "Category of oil barrier" },
    45: {Code: "CATPLE", Description: "Category of pile" },
    46: {Code: "CATPIL", Description: "Category of pilot boarding place" },
    47: {Code: "CATPIP", Description: "Category of pipeline/pipe" },
    48: {Code: "CATPRA", Description: "Category of production area" },
    49: {Code: "CATPYL", Description: "Category of pylon" },
    5: {Code: "BURDEP", Description: "Buried depth" },
    50: {Code: "CATQUA", Description: "Category of quality of data" },
    51: {Code: "CATRAS", Description: "Category of radar station" },
    52: {Code: "CATRTB", Description: "Category of radar transponder beacon" },
    53: {Code: "CATROS", Description: "Category of radio station" },
    54: {Code: "CATTRK", Description: "Category of recommended track" },
    55: {Code: "CATRSC", Description: "Category of rescue station" },
    56: {Code: "CATREA", Description: "Category of restricted area" },
    57: {Code: "CATROD", Description: "Category of road" },
    58: {Code: "CATRUN", Description: "Category of runway" },
    59: {Code: "CATSEA", Description: "Category of sea area" },
    6: {Code: "CALSGN", Description: "Call sign" },
    60: {Code: "CATSLC", Description: "Category of shoreline construction" },
    61: {Code: "CATSIT", Description: "Category of signal station, traffic" },
    62: {Code: "CATSIW", Description: "Category of signal station, warning" },
    63: {Code: "CATSIL", Description: "Category of silo/tank" },
    64: {Code: "CATSLO", Description: "Category of slope" },
    65: {Code: "CATSCF", Description: "Category of small craft facility" },
    66: {Code: "CATSPM", Description: "Category of special purpose mark" },
    67: {Code: "CATTSS", Description: "Category of Traffic Separation Scheme" },
    68: {Code: "CATVEG", Description: "Category of vegetation" },
    69: {Code: "CATWAT", Description: "Category of water turbulence" },
    7: {Code: "CATAIR", Description: "Category of airport/airfield" },
    70: {Code: "CATWED", Description: "Category of weed/kelp" },
    71: {Code: "CATWRK", Description: "Category of wreck" },
    72: {Code: "CATZOC", Description: "Category of zone of confidence in data" },
    73: {Code: "$SPACE", Description: "Character spacing" },
    74: {Code: "$CHARS", Description: "Character specification" },
    75: {Code: "COLOUR", Description: "Colour" },
    76: {Code: "COLPAT", Description: "Colour pattern" },
    77: {Code: "COMCHA", Description: "Communication channel" },
    78: {Code: "$CSIZE", Description: "Compass size" },
    79: {Code: "CPDATE", Description: "Compilation date" },
    8: {Code: "CATACH", Description: "Category of anchorage" },
    80: {Code: "CSCALE", Description: "Compilation scale" },
    81: {Code: "CONDTN", Description: "Condition" },
    82: {Code: "CONRAD", Description: "Conspicuous, radar" },
    83: {Code: "CONVIS", Description: "Conspicuous, visually" },
    84: {Code: "CURVEL", Description: "Current velocity" },
    85: {Code: "DATEND", Description: "Date end" },
    86: {Code: "DATSTA", Description: "Date start" },
    87: {Code: "DRVAL1", Description: "Depth range value 1" },
    88: {Code: "DRVAL2", Description: "Depth range value 2" },
    89: {Code: "DUNITS", Description: "Depth units" },
    9: {Code: "CATBRG", Description: "Category of bridge" },
    90: {Code: "ELEVAT", Description: "Elevation" },
    91: {Code: "ESTRNG", Description: "Estimated range of transmission" },
    92: {Code: "EXCLIT", Description: "Exhibition condition of light" },
    93: {Code: "EXPSOU", Description: "Exposition of sounding" },
    94: {Code: "FUNCTN", Description: "Function" },
    95: {Code: "HEIGHT", Description: "Height" },
    96: {Code: "HUNITS", Description: "Height/length units" },
    97: {Code: "HORACC", Description: "Horizontal accuracy" },
    98: {Code: "HORCLR", Description: "Horizontal clearance" },
    99: {Code: "HORLEN", Description: "Horizontal length" }
};

module.exports = AttributeCodes;
