
let ObjectClasses = {
    1: { Code: "ADMARE", Description: "Administration Area (Named)" },
    10: { Code: "BERTHS", Description: "Berth"},
    100: { Code: "RADRNG", Description: "Radar range"},
    1001: { Code: "BRTFAC", Description: "Berthing facility" },
    1002: { Code: "BUIREL", Description: "Building, religious" },
    1003: { Code: "CAIRNS", Description: "Cairn" },
    1004: { Code: "CEMTRY", Description: "Cemetery" },
    1005: { Code: "CHNWIR", Description: "Chain/Wire" },
    1006: { Code: "CHIMNY", Description: "Chimney" },
    1007: { Code: "DIFFUS", Description: "Diffuser" },
    1008: { Code: "DSHAER", Description: "Dish aerial" },
    1009: { Code: "DUNARE", Description: "Dune" },
    101: { Code: "RADRFL", Description: "Radar reflector" },
    1010: { Code: "DYKARE", Description: "Dyke area" },
    1011: { Code: "DYKCRW", Description: "Dyke crown" },
    1012: { Code: "FSHHAV", Description: "Fish haven" },
    1013: { Code: "FLGSTF", Description: "Flagstaff/Flagpole" },
    1014: { Code: "FLASTK", Description: "Flare stack" },
    1015: { Code: "HILARE", Description: "Hill" },
    1016: { Code: "ITDARE", Description: "Intertidal area" },
    1017: { Code: "LNDPLC", Description: "Landing place" },
    1018: { Code: "LNDSTS", Description: "Landing stairs" },
    1019: { Code: "LITMOI", Description: "Light, moire effect" },
    102: { Code: "RADSTA", Description: "Radar station" },
    1020: { Code: "MSTCON", Description: "Mast" },
    1021: { Code: "MONUMT", Description: "Monument" },
    1022: { Code: "NATARE", Description: "National territorial area" },
    1023: { Code: "PINGOS", Description: "Pingo" },
    1024: { Code: "PRDINS", Description: "Production installation" },
    1025: { Code: "RADDOM", Description: "Radar dome" },
    1026: { Code: "RMPARE", Description: "Ramp" },
    1027: { Code: "RODCRS", Description: "Road crossing" },
    1028: { Code: "ROADPT", Description: "Road part" },
    1029: { Code: "SLTPAN", Description: "Salt pan" },
    103: { Code: "RTPBCN", Description: "Radar transponder beacon" },
    1030: { Code: "SILBUI", Description: "Silo" },
    1031: { Code: "SLIPWY", Description: "Slipway" },
    1032: { Code: "SPOGRD", Description: "Spoil ground" },
    1033: { Code: "TNKCON", Description: "Tank" },
    1034: { Code: "TELPHC", Description: "Telepheric" },
    1035: { Code: "TOWERS", Description: "Tower" },
    1036: { Code: "TREPNT", Description: "Tree" },
    1037: { Code: "TNLENT", Description: "Tunnel entrance" },
    1038: { Code: "VEGARE", Description: "Vegetation area" },
    1039: { Code: "WIRLNE", Description: "Weir" },
    104: { Code: "RDOCAL", Description: "Radio calling-in point" },
    1040: { Code: "WNDMIL", Description: "Windmill" },
    1041: { Code: "WIMCON", Description: "Windmotor" },
    1042: { Code: "ZEMCNT", Description: "Zero metre - contour" },
    1044: { Code: "ACHPNT", Description: "Anchor" },
    105: { Code: "RDOSTA", Description: "Radio station" },
    106: { Code: "RAILWY", Description: "Railway" },
    107: { Code: "RAPIDS", Description: "Rapids" },
    108: { Code: "RCRTCL", Description: "Recommended route centerline" },
    109: { Code: "RECTRC", Description: "Recommended track" },
    11: { Code: "BRIDGE", Description: "Bridge" },
    110: { Code: "RCTLPT", Description: "Recommended traffic lane part" },
    111: { Code: "RSCSTA", Description: "Rescue station" },
    112: { Code: "RESARE", Description: "Restricted area" },
    113: { Code: "RETRFL", Description: "Retro-reflector" },
    114: { Code: "RIVERS", Description: "River" },
    115: { Code: "RIVBNK", Description: "River bank" },
    116: { Code: "ROADWY", Description: "Road" },
    117: { Code: "RUNWAY", Description: "Runway" },
    118: { Code: "SNDWAV", Description: "Sand waves" },
    119: { Code: "SEAARE", Description: "Sea area/named water area" },
    12: { Code: "BUISGL", Description: "Building, single" },
    120: { Code: "SPLARE", Description: "Sea-plane landing area" },
    121: { Code: "SBDARE", Description: "Seabed area" },
    122: { Code: "SLCONS", Description: "Shoreline construction" },
    123: { Code: "SISTAT", Description: "Signal station, traffic" },
    124: { Code: "SISTAW", Description: "Signal station, warning" },
    125: { Code: "SILTNK", Description: "Silo/tank" },
    126: { Code: "SLOTOP", Description: "Slope topline" },
    127: { Code: "SLOGRD", Description: "Sloping ground" },
    128: { Code: "SMCFAC", Description: "Small craft facility" },
    129: { Code: "SOUNDG", Description: "Sounding" },
    13: { Code: "BUAARE", Description: "Built-up area" },
    130: { Code: "SPRING", Description: "Spring" },
    1301: { Code: "M_SSOR", Description: "Survey source" },
    131: { Code: "SQUARE", Description: "Square" },
    132: { Code: "STSLNE", Description: "Straight territorial sea baseline" },
    133: { Code: "SUBTLN", Description: "Submarine transit lane" },
    134: { Code: "SWPARE", Description: "Swept Area" },
    135: { Code: "TESARE", Description: "Territorial sea area" },
    136: { Code: "TS_PRH", Description: "Tidal stream - harmonic prediction" },
    137: { Code: "TS_PNH", Description: "Tidal stream - non-harmonic prediction" },
    138: { Code: "TS_PAD", Description: "Tidal stream panel data" },
    139: { Code: "TS_TIS", Description: "Tidal stream - time series" },
    14: { Code: "BOYCAR", Description: "Buoy, cardinal" },
    140: { Code: "T_HMON", Description: "Tide - harmonic prediction" },
    141: { Code: "T_NHMN", Description: "Tide - non-harmonic prediction" },
    142: { Code: "T_TIMS", Description: "Tide - time series" },
    143: { Code: "TIDEWY", Description: "Tideway" },
    144: { Code: "TOPMAR", Description: "Topmark" },
    145: { Code: "TSELNE", Description: "Traffic separation line" },
    146: { Code: "TSSBND", Description: "Traffic separation scheme boundary" },
    147: { Code: "TSSCRS", Description: "Traffic separation scheme crossing" },
    148: { Code: "TSSLPT", Description: "Traffic separation scheme lane part" },
    149: { Code: "TSSRON", Description: "Traffic separation scheme roundabout" },
    15: { Code: "BOYINB", Description: "Buoy, installation" },
    150: { Code: "TSEZNE", Description: "Traffic separation zone" },
    1505: { Code: "$CLOLN", Description: "Closing line" },
    1507: { Code: "$SHABL", Description: "Shallow water blue" },
    151: { Code: "TUNNEL", Description: "Tunnel" },
    152: { Code: "TWRTPT", Description: "Two-way route part" },
    153: { Code: "UWTROC", Description: "Underwater/awash rock" },
    154: { Code: "UNSARE", Description: "Unsurveyed area" },
    155: { Code: "VEGATN", Description: "Vegetation" },
    156: { Code: "WATTUR", Description: "Water turbulence" },
    157: { Code: "WATFAL", Description: "Waterfall" },
    158: { Code: "WEDKLP", Description: "Weed/Kelp" },
    159: { Code: "WRECKS", Description: "Wreck" },
    16: { Code: "BOYISD", Description: "Buoy, isolated danger" },
    160: { Code: "TS_FEB", Description: "Tidal stream - flood/ebb" },
    161: { Code: "ARCSLN", Description: "Archipelagic Sea Lane" },
    162: { Code: "ASLXIS", Description: "Archipelagic Sea Lane axis" },
    163: { Code: "NEWOBJ", Description: "New object" },
    17: { Code: "BOYLAT", Description: "Buoy, lateral" },
    18: { Code: "BOYSAW", Description: "Buoy, safe water" },
    19: { Code: "BOYSPP", Description: "Buoy, special purpose/general" },
    2: { Code: "AIRARE", Description: "Airport/airfield" },
    20: { Code: "CBLARE", Description: "Cable area" },
    21: { Code: "CBLOHD", Description: "Cable, overhead" },
    22: { Code: "CBLSUB", Description: "Cable, submarine" },
    23: { Code: "CANALS", Description: "Canal" },
    24: { Code: "CANBNK", Description: "Canal bank" },
    25: { Code: "CTSARE", Description: "Cargo transhipment area" },
    26: { Code: "CAUSWY", Description: "Causeway" },
    27: { Code: "CTNARE", Description: "Caution area" },
    28: { Code: "CHKPNT", Description: "Checkpoint" },
    29: { Code: "CGUSTA", Description: "Coastguard station" },
    3: { Code: "ACHBRT", Description: "Anchor berth" },
    30: { Code: "COALNE", Description: "Coastline" },
    300: { Code: "M_ACCY", Description: "Accuracy of data" },
    301: { Code: "M_CSCL", Description: "Compilation scale of data" },
    302: { Code: "M_COVR", Description: "Coverage" },
    303: { Code: "M_HDAT", Description: "Horizontal datum of data" },
    304: { Code: "M_HOPA", Description: "Horizontal datum shift parameters" },
    305: { Code: "M_NPUB", Description: "Nautical publication information" },
    306: { Code: "M_NSYS", Description: "Navigational system of marks" },
    307: { Code: "M_PROD", Description: "Production information" },
    308: { Code: "M_QUAL", Description: "Quality of data" },
    309: { Code: "M_SDAT", Description: "Sounding datum" },
    31: { Code: "CONZNE", Description: "Contiguous zone" },
    310: { Code: "M_SREL", Description: "Survey reliability" },
    311: { Code: "M_UNIT", Description: "Units of measurement of data" },
    312: { Code: "M_VDAT", Description: "Vertical datum of data" },
    32: { Code: "COSARE", Description: "Continental shelf area" },
    33: { Code: "CTRPNT", Description: "Control point" },
    34: { Code: "CONVYR", Description: "Conveyor" },
    35: { Code: "CRANES", Description: "Crane" },
    36: { Code: "CURENT", Description: "Current - non-gravitational" },
    37: { Code: "CUSZNE", Description: "Custom zone" },
    38: { Code: "DAMCON", Description: "Dam" },
    39: { Code: "DAYMAR", Description: "Daymark" },
    4: { Code: "ACHARE", Description: "Anchorage area" },
    40: { Code: "DWRTCL", Description: "Deep water route centerline" },
    400: { Code: "C_AGGR", Description: "Aggregation" },
    401: { Code: "C_ASSO", Description: "Association" },
    402: { Code: "C_STAC", Description: "Stacked on/stacked under" },
    41: { Code: "DWRTPT", Description: "Deep water route part" },
    42: { Code: "DEPARE", Description: "Depth area" },
    43: { Code: "DEPCNT", Description: "Depth contour" },
    44: { Code: "DISMAR", Description: "Distance mark" },
    45: { Code: "DOCARE", Description: "Dock area" },
    46: { Code: "DRGARE", Description: "Dredged area" },
    47: { Code: "DRYDOC", Description: "Dry dock" },
    48: { Code: "DMPGRD", Description: "Dumping ground" },
    49: { Code: "DYKCON", Description: "Dyke" },
    5: { Code: "BCNCAR", Description: "Beacon, cardinal" },
    50: { Code: "EXEZNE", Description: "Exclusive economic zone" },
    500: { Code: "$AREAS", Description: "Cartographic area" },
    501: { Code: "$LINES", Description: "Cartographic line" },
    502: { Code: "$CSYMB", Description: "Cartographic symbol" },
    503: { Code: "$COMPS", Description: "Compass" },
    504: { Code: "$TEXTS", Description: "Text" },
    51: { Code: "FAIRWY", Description: "Fairway" },
    52: { Code: "FNCLNE", Description: "Fence/wall" },
    53: { Code: "FERYRT", Description: "Ferry route" },
    54: { Code: "FSHZNE", Description: "Fishery zone" },
    55: { Code: "FSHFAC", Description: "Fishing facility" },
    56: { Code: "FSHGRD", Description: "Fishing ground" },
    57: { Code: "FLODOC", Description: "Floating dock" },
    58: { Code: "FOGSIG", Description: "Fog signal" },
    59: { Code: "FORSTC", Description: "Fortified structure" },
    6: { Code: "BCNISD", Description: "Beacon, isolated danger" },
    60: { Code: "FRPARE", Description: "Free port area" },
    61: { Code: "GATCON", Description: "Gate" },
    62: { Code: "GRIDRN", Description: "Gridiron" },
    63: { Code: "HRBARE", Description: "Harbour area (administrative)" },
    64: { Code: "HRBFAC", Description: "Harbour facility" },
    65: { Code: "HULKES", Description: "Hulk" },
    66: { Code: "ICEARE", Description: "Ice area" },
    67: { Code: "ICNARE", Description: "Incineration area" },
    68: { Code: "ISTZNE", Description: "Inshore traffic zone" },
    69: { Code: "LAKARE", Description: "Lake" },
    7: { Code: "BCNLAT", Description: "Beacon, lateral" },
    70: { Code: "LAKSHR", Description: "Lake shore" },
    71: { Code: "LNDARE", Description: "Land area" },
    72: { Code: "LNDELV", Description: "Land elevation" },
    73: { Code: "LNDRGN", Description: "Land region" },
    74: { Code: "LNDMRK", Description: "Landmark" },
    75: { Code: "LIGHTS", Description: "Light" },
    76: { Code: "LITFLT", Description: "Light float" },
    77: { Code: "LITVES", Description: "Light vessel" },
    78: { Code: "LOCMAG", Description: "Local magnetic anomaly" },
    79: { Code: "LOKBSN", Description: "Lock basin" },
    8: { Code: "BCNSAW", Description: "Beacon, safe water" },
    80: { Code: "LOGPON", Description: "Log pond" },
    81: { Code: "MAGVAR", Description: "Magnetic variation" },
    82: { Code: "MARCUL", Description: "Marine farm/culture" },
    83: { Code: "MIPARE", Description: "Military practice area" },
    84: { Code: "MORFAC", Description: "Mooring/Warping facility" },
    85: { Code: "NAVLNE", Description: "Navigation line" },
    86: { Code: "OBSTRN", Description: "Obstruction" },
    87: { Code: "OFSPLF", Description: "Offshore platform" },
    88: { Code: "OSPARE", Description: "Offshore production area" },
    89: { Code: "OILBAR", Description: "Oil barrier" },
    9: { Code: "BCNSPP", Description: "Beacon, special purpose/general" },
    90: { Code: "PILPNT", Description: "Pile" },
    91: { Code: "PILBOP", Description: "Pilot boarding place" },
    92: { Code: "PIPARE", Description: "Pipeline area" },
    93: { Code: "PIPOHD", Description: "Pipeline, overhead" },
    94: { Code: "PIPSOL", Description: "Pipeline, submarine/on land" },
    95: { Code: "PONTON", Description: "Pontoon" },
    96: { Code: "PRCARE", Description: "Precautionary area" },
    97: { Code: "PRDARE", Description: "Production/storage area" },
    98: { Code: "PYLONS", Description: "Pylon/bridge support" },
    99: { Code: "RADLNE", Description: "Radar line" }
};

module.exports = ObjectClasses;